Atificial Neural Network

Importing Libraries

In [17]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [18]:
tf.__version__

'2.3.0'

Data Preprocessing

In [19]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


Encoding Categorical Data

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Spliting

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN

In [24]:
ann = tf.keras.models.Sequential()

add first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

add second hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

add output layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training ANN

Compiling

In [28]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training the ANN on the Training set

In [29]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5480 - accuracy: 0.7952
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4884 - accuracy: 0.7958
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4537 - accuracy: 0.7995
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4346 - accuracy: 0.8029
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4241 - accuracy: 0.8139
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4155 - accuracy: 0.8179
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4085 - accuracy: 0.8230
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4028 - accuracy: 0.8248
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3969 - accuracy: 0.8289
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3920 - accura

Print one single solution

In [30]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Predicting

In [31]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.8)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion Matrix

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1586    9]
 [ 295  110]]


0.848